### ISSUE TITLE
Nice vim configs

### ISSUE THREAD

**Issue by wbaik** [virgax7/configs#1]
Nice stuff. Didn't know about `hlsearch`. What's your recommended way of turning the `highlights` off? I found https://vi.stackexchange.com/questions/8741/how-to-automatically-turn-off-hlsearch-after-im-done-searching , wonder key mapping is the only way...

**Comment by virgax7** [comment]
Haha thanks, I updated these things a lot over the time, but grab the latest copy. All of the commands are short circuited in verbose more for performance. I was annoyed by that as well, but I think the shortcut I had is prob the easiest way I came up with.

I think you can customize your vim with vim scripts, but I don't think its worth the time investing xD

**Comment by virgax7** [comment]
"set no highlight
:nnoremap <Esc>n :noh<Cr>

**Comment by wbaik** [comment]
I see. Thanks. I originally used those `vim awesome` stuff... `https://github.com/amix/vimrc`, which usually have a bunch of stuff I am not aware of. Now I'm just sticking witgh JetBrain products, with their default vim-add on. The base setting suits me well enough I guess... haha
